# Generated by Django 2.0.2 on 2018-03-23 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Enter file name', max_length=50, verbose_name='File name')),
                ('upload_date', models.DateTimeField(verbose_name='Date of file upload')),
                ('link', models.CharField(max_length=50, verbose_name='Link to file')),
                ('path_on_disk', models.CharField(max_length=50, verbose_name='Path on disk')),
                ('time_to_live', models.DurationField()),
                ('file_type', models.CharField(help_text='Enter file type', max_length=50, verbose_name='File type')),
                ('size', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
