# Generated by Django 2.0.2 on 2018-03-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='time_to_live',
            field=models.DateTimeField(null=True, verbose_name='Delete Date'),
        ),
    ]
