# Generated by Django 2.0.2 on 2018-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_auto_20180330_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='time_to_live',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delete Date'),
        ),
    ]
