# Generated by Django 2.0.4 on 2018-05-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='link',
        ),
        migrations.RemoveField(
            model_name='file',
            name='path_on_disk',
        ),
    ]
